# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


runner:
  train_data_dir: "data/sample_data/train"
  train_reader_path: "criteo_reader" # importlib format
  use_gpu: False
  use_auc: True
  train_batch_size: 16
  epochs: 2
  print_interval: 2
  #model_init_path: "output_model/0" # init model
  model_save_path: "output_model_fgcnn"
  test_data_dir: "data/sample_data/train"
  infer_reader_path: "criteo_reader" # importlib format
  infer_batch_size: 16
  infer_load_path: "output_model_fgcnn"
  infer_start_epoch: 0
  infer_end_epoch: 2

# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: Adagrad
    learning_rate: 0.001
    strategy: async
  # user-defined <key, value> pairs
  sparse_inputs_slots: 27
  sparse_feature_size: [27, 92, 172, 157, 12, 7, 183, 19, 2, 142, 173, 170, 166, 14, 170, 168, 9, 127, 44, 4, 169, 6, 10, 125, 20, 90]
  sparse_feature_name: ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22', 'C23', 'C24', 'C25', 'C26']
  sparse_feature_dim: 4
  dense_input_dim: 13
  conv_kernel_width: [7, 7, 7, 7]
  conv_filters: [14, 16, 18, 20]
  new_maps: [3, 3, 3, 3]
  pooling_width: [2, 2, 2, 2]
  stride: [1, 1]
  dnn_hidden_units: [128]
  dnn_dropout: 0.0